const API_URL="https://script.google.com/macros/s/AKfycbyM3mhup2rSWXeodZJMfFETAegn5VMcznZi6YRlIsiB2meQhSI5l-BByaUaH3dhzEZFng/exec",$=s=>document.querySelector(s);let raw=[];
const S=[["Capricornio","♑"],["Acuario","♒"],["Piscis","♓"],["Aries","♈"],["Tauro","♉"],["Géminis","♊"],["Cáncer","♋"],["Leo","♌"],["Virgo","♍"],["Libra","♎"],["Escorpio","♏"],["Sagitario","♐"]],B=[20,19,21,20,21,21,23,23,23,23,22,22];
function z(v){let p=String(v||"").split("-"),m=+p[1],d=+p[2];return m&&d?(d<B[m-1]?S[m-1]:S[m%12]):["Sin dato","✦"]}
function dt(v){let m=String(v||"").match(/(\d{1,2})\/(\d{1,2})\/(\d{4})\s+(\d{1,2}):(\d{2})/);return m?new Date(+m[3],+m[2]-1,+m[1],+m[4],+m[5]):null}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function test(r){return String(r.ID||"").startsWith("TEST-")||String(r.ORIGEN_QR||"").toUpperCase()==="PRUEBA"}
function counts(a,fn){let o={};a.forEach(x=>{let k=fn(x)||"Sin dato";o[k]=(o[k]||0)+1});return Object.entries(o).sort((a,b)=>b[1]-a[1])}
async function load(){try{$("#status").textContent="Sincronizando…";let r=await fetch(API_URL+"?t="+Date.now(),{cache:"no-store"}),d=await r.json();if(!d.ok)throw Error(d.error||"API");raw=d.registros||[];render();$("#status").textContent="Conectado · "+raw.length+" registros recibidos";$("#status").className="";$("#updated").textContent="Actualizado "+new Date().toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit"})}catch(e){$("#status").textContent="Error de conexión · "+e.message;$("#status").className="error"}}
function render(){let a=$("#tests").checked?raw:raw.filter(r=>!test(r)),now=new Date();$("#total").textContent=a.length;$("#today").textContent=a.filter(r=>{let d=dt(r.FECHA_REGISTRO);return d&&d.toDateString()==now.toDateString()}).length;$("#pending").textContent=a.filter(r=>String(r.ESTATUS).toUpperCase()=="PENDIENTE").length;$("#sources").textContent=new Set(a.map(r=>r.ORIGEN_QR||"DIRECTO")).size;hours(a);zs(a);$("#origins").innerHTML=rank(counts(a,r=>r.ORIGEN_QR||"DIRECTO"));$("#places").innerHTML=rank(counts(a,r=>r.LUGAR_NACIMIENTO||"Sin dato"));recent(a)}
function hours(a){let hs=Array.from({length:12},(_,i)=>i+8),c=Object.fromEntries(hs.map(h=>[h,0]));a.forEach(r=>{let d=dt(r.FECHA_REGISTRO);if(d&&c[d.getHours()]!==undefined)c[d.getHours()]++});let mx=Math.max(1,...Object.values(c));$("#bars").innerHTML=hs.map(h=>`<div class="col"><i>${c[h]||""}</i><div class="bar" style="height:${Math.max(3,c[h]/mx*150)}px"></div><small>${h}h</small></div>`).join("");let p=Object.entries(c).sort((a,b)=>b[1]-a[1])[0];$("#peak").textContent=p&&p[1]?`Pico ${p[0]}:00 · ${p[1]}`:"Esperando actividad"}
function zs(a){let c=counts(a,r=>z(r.FECHA_NACIMIENTO)[0]),t=c[0]||["—",0],g=(S.find(x=>x[0]==t[0])||["","✦"])[1];$("#glyph").textContent=g;$("#sign").textContent=t[0];$("#zlegend").innerHTML=c.slice(0,8).map(x=>`<div class="lr"><span>${esc(x[0])}</span><b>${x[1]}</b></div>`).join("")||'<div class="empty">Sin datos</div>'}
function rank(it){let mx=Math.max(1,...it.map(x=>x[1]));return it.slice(0,6).map(x=>`<div class="rank"><span class="rn">${esc(x[0])}</span><div class="track"><div class="fill" style="width:${x[1]/mx*100}%"></div></div><span>${x[1]}</span></div>`).join("")||'<div class="empty">Sin datos</div>'}
function recent(a){a=[...a].sort((x,y)=>(dt(y.FECHA_REGISTRO)||0)-(dt(x.FECHA_REGISTRO)||0)).slice(0,8);$("#rows").innerHTML=a.map(r=>{let s=z(r.FECHA_NACIMIENTO);return `<tr><td><strong>${esc(r.NOMBRE)}</strong><small>${esc(r.ID)}</small></td><td>${s[1]} ${esc(s[0])} · ${esc(r.LUGAR_NACIMIENTO)}</td><td><span class="badge">${esc(r.ORIGEN_QR||"DIRECTO")}</span></td><td><span class="badge">${esc(r.ESTATUS||"—")}</span></td><td>${esc(r.FECHA_REGISTRO)}</td></tr>`}).join("")||'<tr><td colspan="5" class="empty">Sin registros</td></tr>'}
$("#refresh").onclick=load;$("#tests").onchange=render;load();setInterval(load,30000);
const cv=$("#cosmos"),cx=cv.getContext("2d");let st=[];function rs(){cv.width=innerWidth*devicePixelRatio;cv.height=innerHeight*devicePixelRatio;cx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);st=Array.from({length:Math.min(140,innerWidth/8)},()=>[Math.random()*innerWidth,Math.random()*innerHeight,Math.random()*1.2+.15,Math.random()*.55+.1])}function dr(){cx.clearRect(0,0,innerWidth,innerHeight);st.forEach(s=>{cx.globalAlpha=s[3];cx.fillStyle="#d9dcff";cx.beginPath();cx.arc(s[0],s[1],s[2],0,7);cx.fill()});cx.globalAlpha=1;requestAnimationFrame(dr)}onresize=rs;rs();dr();