let currentPage=1,PAGE_SIZE=10,searchTerm="";const API_URL="https://script.google.com/macros/s/AKfycbyM3mhup2rSWXeodZJMfFETAegn5VMcznZi6YRlIsiB2meQhSI5l-BByaUaH3dhzEZFng/exec",$=s=>document.querySelector(s);let raw=[];
const S=[["Capricornio","♑"],["Acuario","♒"],["Piscis","♓"],["Aries","♈"],["Tauro","♉"],["Géminis","♊"],["Cáncer","♋"],["Leo","♌"],["Virgo","♍"],["Libra","♎"],["Escorpio","♏"],["Sagitario","♐"]],B=[20,19,21,20,21,21,23,23,23,23,22,22];
function z(v){let p=String(v||"").split("-"),m=+p[1],d=+p[2];return m&&d?(d<B[m-1]?S[m-1]:S[m%12]):["Sin dato","✦"]}
function dt(v){let m=String(v||"").match(/(\d{1,2})\/(\d{1,2})\/(\d{4})\s+(\d{1,2}):(\d{2})/);return m?new Date(+m[3],+m[2]-1,+m[1],+m[4],+m[5]):null}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function isTest(r){return String(r.ID||"").startsWith("TEST-")||String(r.ORIGEN_QR||"").toUpperCase()==="PRUEBA"}
function counts(a,fn){let o={};a.forEach(x=>{let k=fn(x)||"Sin dato";o[k]=(o[k]||0)+1});return Object.entries(o).sort((a,b)=>b[1]-a[1])}
function animateNumber(el,n){let s=performance.now(),from=Number(el.textContent)||0,d=650;function f(t){let p=Math.min(1,(t-s)/d),e=1-Math.pow(1-p,3);el.textContent=Math.round(from+(n-from)*e);if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f)}
async function load(){try{$("#status").textContent="Sincronizando universo…";let r=await fetch(API_URL+"?t="+Date.now(),{cache:"no-store"}),d=await r.json();if(!d.ok)throw Error(d.error||"API");raw=d.registros||[];render();$("#status").textContent="Conectado · "+raw.length+" señales recibidas";$("#status").className="";$("#updated").textContent="Actualizado "+new Date().toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit"})}catch(e){$("#status").textContent="Error de conexión · "+e.message;$("#status").className="error"}}
function render(){let a=$("#tests").checked?raw:raw.filter(r=>!isTest(r)),now=new Date();animateNumber($("#total"),a.length);animateNumber($("#today"),a.filter(r=>{let d=dt(r.FECHA_REGISTRO);return d&&d.toDateString()==now.toDateString()}).length);animateNumber($("#pending"),a.filter(r=>String(r.ESTATUS).toUpperCase()=="PENDIENTE").length);animateNumber($("#sources"),new Set(a.map(r=>r.ORIGEN_QR||"DIRECTO")).size);hours(a);zs(a);$("#origins").innerHTML=rank(counts(a,r=>r.ORIGEN_QR||"DIRECTO"));$("#places").innerHTML=rank(counts(a,r=>r.LUGAR_NACIMIENTO||"Sin dato"));recent(a)}
function hours(a){let hs=Array.from({length:12},(_,i)=>i+8),c=Object.fromEntries(hs.map(h=>[h,0]));a.forEach(r=>{let d=dt(r.FECHA_REGISTRO);if(d&&c[d.getHours()]!==undefined)c[d.getHours()]++});let mx=Math.max(1,...Object.values(c));$("#bars").innerHTML=hs.map(h=>`<div class="col"><i>${c[h]||""}</i><div class="bar" style="height:${Math.max(4,c[h]/mx*155)}px"></div><small>${h}:00</small></div>`).join("");let p=Object.entries(c).sort((a,b)=>b[1]-a[1])[0];$("#peak").textContent=p&&p[1]?`PICO · ${p[0]}:00 · ${p[1]}`:"ESPERANDO SEÑAL"}
function zs(a){let c=counts(a,r=>z(r.FECHA_NACIMIENTO)[0]),t=c[0]||["—",0],g=(S.find(x=>x[0]==t[0])||["","✦"])[1];$("#glyph").textContent=g;$("#sign").textContent=t[0];$("#zlegend").innerHTML=c.slice(0,8).map(x=>`<div class="lr"><span>${esc(x[0])}</span><b>${x[1]}</b></div>`).join("")||'<div class="empty">Esperando constelaciones…</div>'}
function rank(it){let mx=Math.max(1,...it.map(x=>x[1]));return it.slice(0,6).map(x=>`<div class="rank"><span class="rn">${esc(x[0])}</span><div class="track"><div class="fill" style="width:${x[1]/mx*100}%"></div></div><b>${x[1]}</b></div>`).join("")||'<div class="empty">Esperando datos…</div>'}
function recent(a){let all=[...a].sort((x,y)=>(dt(y.FECHA_REGISTRO)||0)-(dt(x.FECHA_REGISTRO)||0)),q=searchTerm.trim().toLowerCase();if(q)all=all.filter(r=>[r.NOMBRE,r.ID,r.LUGAR_NACIMIENTO,r.ORIGEN_QR,r.ESTATUS].some(v=>String(v||"").toLowerCase().includes(q)));let pages=Math.max(1,Math.ceil(all.length/PAGE_SIZE));currentPage=Math.max(1,Math.min(currentPage,pages));let page=all.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE);$("#shownCount").textContent=all.length;$("#rows").innerHTML=page.map(r=>{let s=z(r.FECHA_NACIMIENTO);return `<tr><td><strong>${esc(r.NOMBRE)}</strong><small>${esc(r.ID)}</small></td><td>${s[1]} ${esc(s[0])} · ${esc(r.LUGAR_NACIMIENTO)}</td><td><span class="badge">${esc(r.ORIGEN_QR||"DIRECTO")}</span></td><td><span class="badge">${esc(r.ESTATUS||"—")}</span></td><td>${esc(r.FECHA_REGISTRO)}</td></tr>`}).join("")||`<tr><td colspan="5" class="empty">${q?"No encontramos coincidencias.":"Esperando primeras conexiones…"}</td></tr>`;$("#pageInfo").textContent=`Página ${currentPage} de ${pages} · ${all.length} registro${all.length===1?"":"s"}`;$("#prevPage").disabled=currentPage<=1;$("#nextPage").disabled=currentPage>=pages;pagesUI(pages)}
function pagesUI(p){let n=[];if(p<=5){for(let i=1;i<=p;i++)n.push(i)}else{n=[1];let a=Math.max(2,currentPage-1),b=Math.min(p-1,currentPage+1);if(a>2)n.push("…");for(let i=a;i<=b;i++)n.push(i);if(b<p-1)n.push("…");n.push(p)}$("#pageNumbers").innerHTML=n.map(x=>x==="…"?'<span class="page-dots">…</span>':`<button class="${x===currentPage?"active":""}" data-page="${x}">${x}</button>`).join("");document.querySelectorAll("#pageNumbers button").forEach(b=>b.onclick=()=>{currentPage=+b.dataset.page;render()})}
$("#search").addEventListener("input",e=>{searchTerm=e.target.value;currentPage=1;render()});$("#prevPage").onclick=()=>{if(currentPage>1){currentPage--;render()}};$("#nextPage").onclick=()=>{currentPage++;render()};
$("#refresh").onclick=()=>{let b=$("#refresh");b.style.transform="rotate(180deg)";load();setTimeout(()=>b.style.transform="",500)};$("#tests").onchange=render;load();setInterval(load,30000);
const cv=$("#cosmos"),cx=cv.getContext("2d");let stars=[],shoot=null;function resize(){let d=Math.min(devicePixelRatio,2);cv.width=innerWidth*d;cv.height=innerHeight*d;cx.setTransform(d,0,0,d,0,0);stars=Array.from({length:Math.min(220,Math.floor(innerWidth/5))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.25+.15,a:Math.random()*.58+.1,s:Math.random()*.012+.003}))}function draw(t){cx.clearRect(0,0,innerWidth,innerHeight);stars.forEach(s=>{s.a+=Math.sin(t*s.s)*.001;cx.globalAlpha=Math.max(.08,Math.min(.72,s.a));cx.fillStyle="#dfe2ff";cx.beginPath();cx.arc(s.x,s.y,s.r,0,7);cx.fill()});if(!shoot&&Math.random()<.002)shoot={x:Math.random()*innerWidth*.65,y:Math.random()*innerHeight*.35,l:0};if(shoot){shoot.l+=12;cx.globalAlpha=Math.max(0,1-shoot.l/220);let g=cx.createLinearGradient(shoot.x,shoot.y,shoot.x+shoot.l,shoot.y+shoot.l*.35);g.addColorStop(0,"transparent");g.addColorStop(1,"#cfd6ff");cx.strokeStyle=g;cx.lineWidth=1;cx.beginPath();cx.moveTo(shoot.x,shoot.y);cx.lineTo(shoot.x+shoot.l,shoot.y+shoot.l*.35);cx.stroke();if(shoot.l>220)shoot=null}cx.globalAlpha=1;requestAnimationFrame(draw)}addEventListener("resize",resize);resize();requestAnimationFrame(draw);